# Generated by Django 2.2.12 on 2020-05-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseid', models.AutoField(db_column='CourseId', primary_key=True, serialize=False)),
                ('courseno', models.IntegerField(blank=True, db_column='CourseNo', null=True)),
                ('subject', models.TextField(blank=True, db_column='Subject', null=True)),
                ('title', models.TextField(blank=True, db_column='Title', null=True)),
            ],
            options={
                'db_table': 'Course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gpa',
            fields=[
                ('term', models.TextField(blank=True, db_column='Term', null=True)),
                ('value', models.FloatField(blank=True, db_column='Value', null=True)),
                ('courseid', models.IntegerField(blank=True, db_column='CourseId', null=True)),
                ('classsize', models.IntegerField(blank=True, db_column='ClassSize', null=True)),
                ('year', models.IntegerField(blank=True, db_column='Year', null=True)),
                ('professorid', models.IntegerField(blank=True, db_column='ProfessorId', null=True)),
                ('gpaid', models.AutoField(db_column='GPAId', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'GPA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('department', models.TextField(blank=True, db_column='Department', null=True)),
                ('professorid', models.AutoField(db_column='ProfessorId', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Professor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, db_column='UserName', null=True)),
                ('password', models.TextField(blank=True, db_column='Password', null=True)),
                ('isadmin', models.IntegerField(blank=True, db_column='IsAdmin', null=True)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoursePrereqModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.TextField()),
                ('Prereq', models.TextField()),
                ('AvgGpa', models.CharField(max_length=50)),
            ],
        ),
    ]
