# Generated by Django 3.0.4 on 2020-03-10 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=5)),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('subject', 'number')},
            },
        ),
        migrations.CreateModel(
            name='GPA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('term', models.CharField(max_length=10)),
                ('professor', models.CharField(max_length=50)),
                ('gpa', models.FloatField()),
                ('class_size', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Courses')),
            ],
            options={
                'unique_together': {('course', 'year', 'term', 'professor')},
            },
        ),
    ]
